minVersion: 2.6.0
changelogPolicy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
  # The first registry needs to be added manually otherwise the CI release will fail
  # We can uncomment this after we did our first release and added the registry manually
  # - name: registry
  #   sdks:
  #     npm:@sentry/lynx-react:
  #       includeNames: /^sentry-lynx-react-\d.*\.tgz$/
